apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kubescape
    server: {{ .Values.spec.destination.server }}
  source:
    path: charts/kubescape-operator
    repoURL: 'https://github.com/kubescape/helm-charts'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: server
          value: api.armosec.io
        - name: clusterName
          value: {{ .Values.spec.armosec.clusterName }}
        - name: account
          value: {{ .Values.spec.armosec.account }}
        - name: accessKey
          value: {{ .Values.spec.armosec.accessKey }}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated: 
      prune: false 
      selfHeal: true 
  ignoreDifferences:
    - group: core
      kind: ConfigMap
      name: ks-cloud-config
      namespace: kubescape
      jsonPointers:
        - /data
        - /metadata
